/************ Update: Schemas ***************/

COMMENT ON SCHEMA public IS NULL;



/************ Add: Sequences ***************/

/* Autogenerated Sequences */

CREATE SEQUENCE bitacora_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE credencial_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE recordar_me_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE usuario_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE usuario_credencial_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';



/************ Update: Tables ***************/

/******************** Add Table: bitacora ************************/

/* Build Table Structure */
CREATE TABLE bitacora
(
	id BIGINT DEFAULT nextval('public.bitacora_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	accion VARCHAR(80) NOT NULL,
	tabla VARCHAR(80) NOT NULL,
	registro BIGINT NULL,
	observacion VARCHAR(1024) NULL,
	fecha TIMESTAMP DEFAULT now() NOT NULL
);

/* Add Primary Key */
ALTER TABLE bitacora ADD CONSTRAINT pkbitacora
	PRIMARY KEY (id);

/* Add Indexes */
CREATE INDEX "bitacora_fecha_Idx" ON bitacora (fecha);

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora (usuario_id);


/******************** Add Table: credencial ************************/

/* Build Table Structure */
CREATE TABLE credencial
(
	id BIGINT DEFAULT nextval('public.credencial_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

/* Add Primary Key */
ALTER TABLE credencial ADD CONSTRAINT pkcredencial
	PRIMARY KEY (id);


/******************** Add Table: recordar_me ************************/

/* Build Table Structure */
CREATE TABLE recordar_me
(
	id BIGINT DEFAULT nextval('public.recordar_me_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	ip_address VARCHAR(50) NOT NULL,
	hash_cookie VARCHAR(32) NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

/* Add Primary Key */
ALTER TABLE recordar_me ADD CONSTRAINT pkrecordar_me
	PRIMARY KEY (id);

/* Add Indexes */
CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me (ip_address, hash_cookie);

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me (usuario_id);


/******************** Add Table: usuario ************************/

/* Build Table Structure */
CREATE TABLE usuario
(
	id BIGINT DEFAULT nextval('public.usuario_id_seq'::regclass) NOT NULL,
	user_name VARCHAR(80) NOT NULL,
	password VARCHAR(32) NOT NULL,
	actived BOOL DEFAULT 't' NOT NULL,
	last_login_at TIMESTAMP NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

/* Add Primary Key */
ALTER TABLE usuario ADD CONSTRAINT pkusuario
	PRIMARY KEY (id);

/* Add Comments */
COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';

/* Add Indexes */
CREATE INDEX "usuario_actived_Idx" ON usuario (actived);

CREATE INDEX "usuario_deleted_at_Idx" ON usuario (deleted_at);

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario (user_name);

CREATE INDEX "usuario_user_name_password_Idx" ON usuario (user_name, password);


/******************** Add Table: usuario_credencial ************************/

/* Build Table Structure */
CREATE TABLE usuario_credencial
(
	id BIGINT DEFAULT nextval('public.usuario_credencial_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	credencial_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

/* Add Primary Key */
ALTER TABLE usuario_credencial ADD CONSTRAINT pkusuario_credencial
	PRIMARY KEY (id);

/* Add Indexes */
CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial (credencial_id);

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial (usuario_id);

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial (usuario_id, credencial_id);


/************ Add Foreign Keys ***************/

/* Add Foreign Key: fk_bitacora_usuario */
ALTER TABLE bitacora ADD CONSTRAINT fk_bitacora_usuario
	FOREIGN KEY (usuario_id) REFERENCES usuario (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_recordar_me_usuario */
ALTER TABLE recordar_me ADD CONSTRAINT fk_recordar_me_usuario
	FOREIGN KEY (usuario_id) REFERENCES usuario (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_usuario_credencial_credencial */
ALTER TABLE usuario_credencial ADD CONSTRAINT fk_usuario_credencial_credencial
	FOREIGN KEY (credencial_id) REFERENCES credencial (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

/* Add Foreign Key: fk_usuario_credencial_usuario */
ALTER TABLE usuario_credencial ADD CONSTRAINT fk_usuario_credencial_usuario
	FOREIGN KEY (usuario_id) REFERENCES usuario (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

-- ----------------------------
--  Records of "credencial"
-- ----------------------------
BEGIN;
INSERT INTO "credencial" (nombre) VALUES ('admin');
INSERT INTO "credencial" (nombre) VALUES ('usuario');
COMMIT;

-- ----------------------------
--  Records of "usuario" admin - 123
-- ----------------------------
BEGIN;
INSERT INTO "usuario" (user_name, password, actived, last_login_at) VALUES ('admin', '202cb962ac59075b964b07152d234b70', 't', null);
COMMIT;

-- ----------------------------
--  Records of "usuario_credencial"
-- ----------------------------
BEGIN;
INSERT INTO "usuario_credencial" (usuario_id, credencial_id) VALUES (1, 1);
COMMIT;